#!/bin/sh

# DL
echo "daemontoolsをダウンロード"
wget http://cr.yp.to/daemontools/daemontools-0.76.tar.gz
tar xvfz daemontools-0.76.tar.gz
mv admin/daemontools-0.76 .
rmdir admin
cd daemontools-0.76

# patchをあてる
echo "daemontoolsにパッチをあてる"
wget http://www.nslabs.jp/archives/daemontools-0.76-q1.diff
patch -s -p1 <daemontools-0.76-q1.diff
package/install

echo "
save to /etc/init/hoge.conf
--------
start on startup
respawn
exec /command/svscanboot start
"
