#!/bin/sh

# rails consoleで日本語入力できるようにする
# readlineのバージョンによって、パスがかわるかも。

# brew install readline
# 以下fix version
READ_LINE='/usr/local/Cellar/readline/6.2.4/lib/libreadline.dylib'
READ_LINE_BUNDLE="$HOME/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/x86_64-darwin12.2.0/readline.bundle"
# LIBEDIT=`otool -L $READ_LINE_BUNDLE | grep libedit | sed 's/(.*)//g'`
# なぜか上記だと無理
LIBEDIT=/usr/lib/libedit.3.dylib
install_name_tool -change $LIBEDIT $READ_LINE $READ_LINE_BUNDLE
