#!/usr/bin/env bash

YARN_VERSION='0.18.0'

if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
  echo "Download and install Yarn."
  curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  echo 'Please append "export PATH=$HOME/.yarn/bin:$PATH" to your shellrc.'
else
  echo "The correct version of Yarn is already installed."
fi
