#!/bin/sh

PYTHON_VERSION=2.7.18
PYTHON3_VERSION=3.9.7
RUBY_VERSION=2.7.4

cd $HOME
brew install --HEAD neovim
npm install -g neovim
$HOME/.pyenv/versions/$PYTHON3_VERSION/bin/python -m pip install pynvim
$HOME/.pyenv/versions/$PYTHON_VERSION/bin/python -m pip install pynvim

if [ ! -f $HOME/.config/nvim/init.vim ]; then
    mkdir -p ~/.config/nvim
    ln -s $HOME/.vim/nvimrc ~/.config/nvim/init.vim
fi

gem install neovim

pyenv install $PYTHON3_VERSION
pyenv global $PYTHON3_VERSION
pip3 install --upgrade --force-reinstall neovim --user

pyenv rehash
