#!/bin/sh

cd $HOME
brew install --HEAD neovim

if [ ! -f $HOME/.config/nvim/init.vim ]; then
    mkdir -p ~/.config/nvim
    ln -s $HOME/.vim/nvimrc ~/.config/nvim/init.vim
fi

gem install neovim

pyenv install 3.5.2
pyenv global 3.5.2
pip3 install --upgrade --force-reinstall neovim --user

pyenv rehash
