#!/bin/sh

if [ -d $HOME/.nodenv ]
then
    echo "nodenvフォルダは~/.nodenvにインストール済みです"
else
    git clone https://github.com/nodenv/nodenv.git ~/.nodenv
    mkdir -p ~/.nodenv/plugins
    cd ~/.nodenv/plugins
    git clone https://github.com/nodenv/node-build
fi
