#!/bin/sh

sudo ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.8.xctoolchain
brew install node
source ~/.zshrc
npm install -g coffee-script
coffee -h
