#!/bin/sh

#rubyのインスコ #好きなバージョンでok
RUBIES=( 1.9.3-p194 1.9.2-p290)
cd $HOME
git clone git://github.com/sstephenson/rbenv.git ~/.rbenv

if [ -x `which rbenv` ];then
    echo 'rbenvをインストールします'
    mkdir -p ~/.rbenv/plugins
    cd ~/.rbenv/plugins
    git clone git://github.com/sstephenson/ruby-build.git
    git clone git://github.com/tpope/rbenv-ctags.git
    git clone git://github.com/jamis/rbenv-gemset.git
    echo 'export PATH="$HOME/.rbenv/bin/:$HOME/.rbenv:$PATH"'
    echo 'eval "$(rbenv init -)"'

    for version in ${RUBIES[@]}
    do
        rbenv install $version
    done

    #好きなバージョンでok
    rbenv global 1.9.3-p194
    rbenv rehash
fi


