#!/bin/sh

cd $HOME
git clone git://github.com/sstephenson/rbenv.git ~/.rbenv

brew install readline
brew link --force readline

if [ -x `which rbenv` ];then
    echo 'rbenvをインストールします'
    mkdir -p ~/.rbenv/plugins
    cd ~/.rbenv/plugins
    git clone git://github.com/sstephenson/ruby-build.git

    echo "copy-paste this to ~/.zshrc"
    echo 'export PATH="$HOME/.rbenv/bin/:$HOME/.rbenv:$PATH"'
    echo 'eval "$(rbenv init -)"'

    rbenv rehash
    RUBY_CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl` --enable-shared --with-readline-dir=`brew --prefix readline` --with-libyaml-dir=/usr/local" rbenv install 3.2.0
fi
