augroup MyGvimSetting
  autocmd!
  " autocmd VimEnter * set guifont=Ricty\ Regular\ for\ Powerline:h16
augroup END

syntax on
set imdisable

nnoremap ¥ \
inoremap ¥ \
cnoremap ¥ \
snoremap ¥ \

augroup MyGuiWindow
  autocmd!
  autocmd VimEnter set guioptions-=egLrm
augroup END
