set runtimepath^=$HOME/.vim runtimepath+=$HOME/.vim/after
source $HOME/.vim/vimrc
set termguicolors
set clipboard=unnamedplus

if executable('pyenv')
  let g:python_host_prog = system('pyenv which python')
else
  let g:python_host_prog = 'python'
endif

if executable('rbenv')
  let g:ruby_host_prog = system('rbenv which ruby')
else
  let g:python_host_prog = 'ruby'
endif

set runtimepath+=/usr/local/share/nvim/runtime
set runtimepath+=$HOME/.vim

nnoremap <Space><Space>s :<C-U>source ~/.vim/nvimrc<CR>

" deoplete
let g:deoplete#enable_at_startup = 1
