set runtimepath^=$HOME/.vim runtimepath+=$HOME/.vim/after
source $HOME/.vim/vimrc
set termguicolors
set clipboard+=unnamedplus

if executable('pyenv')
  let g:python3_host_prog = $HOME . '/.pyenv/versions/3.10.0/bin/python'
  let g:python_host_prog = $HOME . '/.pyenv/versions/2.9.14/bin/python'
else
  let g:python_host_prog = 'python'
endif

if executable('rbenv')
  " let g:ruby_host_prog = system('rbenv which ruby')
  let g:ruby_host_prog = $HOME . '/.rbenv/versions/3.1.2/bin/ruby'
else
  let g:ruby_host_prog = 'ruby'
endif

set runtimepath+=/usr/local/share/nvim/runtime
set runtimepath+=$HOME/.vim

nnoremap <Space><Space>s :<C-U>source ~/.vim/nvimrc<CR>

" deoplete
let g:deoplete#enable_at_startup = 1
