#!/bin/sh

directory=$1
http_skel=$2
result=()

echo "output directory is ${directory}"
echo "http_skel is ${http_skel}"
echo ''

if [ ! -e ${http_skel} ]; then
    echo "!!! not found http_skel."
    exit
fi

read -p "create config files? y/n " yn
if [ $yn = "y" -o $yn = "Y" ]; then
    echo 'mkdir config ...done'
    mkdir -p config

    echo 'create config files.'
    for dir in `ls ${directory}`
    do
        if [ -d ${directory}${dir} ]; then
            dirname=${dir%/*}
            domain_name="${dirname}.localhost"
            output="config/${domain_name}.conf"
            target_dir="${directory}${dirname}"
            cat ${http_skel} | sed -e "s!/home/domain/www!${target_dir}!" | sed -e "s/domain/${domain_name}/" > $output
            # sed -ie "1s!^!NameVirtualHost ${domain_name}:80!" $output

            echo "create ${domain_name}.conf to config/ ...done"

            result+=(${domain_name})
        fi
    done

    echo ''
    echo "/etc/hosts に追記してください"
    for domain in ${result[@]}
    do
        echo "127.0.0.1     ${domain}"
    done
fi
