#!/bin/sh

# define name and password
name=$1
password=$(mkpasswd -l 32 -s 0)

# 作成するディレクトリ
user_dir="/home/${name}"
git_dir="${user_dir}/git.git"
www_dir="${user_dir}/www"
ssh_dir="${user_dir}/.ssh"

# ディレクトリがある場合処理を中止
if [ -e ${user_dir} ]
then
    echo "既にユーザーかディレクトリが存在します。"
    exit
fi

read -p "create ${name}?" yn
if [ $yn = "y" -o $yn = "Y" ]; then
    /usr/sbin/useradd $name
    echo "password = " $password

    # permission
    chmod 750 /home/$name
    chown -R :apache /home/$name

    cat http_skel.conf | sed -e "s/domain/${name}/" > /etc/httpd/conf.d/${name}.conf

    # gitを構築
    mkdir -p $git_dir
    git init --bare $git_dir
    # cat "(cd ${www_dir};git --git-dir=.git pull;)" > "${git_dir}/hooks/post-receive"
    cat post-receive | sed -e "s?git_directory?${www_dir}?" > "${git_dir}/hooks/post-receive"
    chmod +x "${git_dir}/hooks/post-receive"
    rm -rf $www_dir
    git clone $git_dir $www_dir
    chown -R $name $www_dir $git_dir

    # sshを設定
    chmod 755 ${user_dir}
    mkdir -p ${ssh_dir}
    chmod 755 ${ssh_dir}
    cp authorized_keys ${ssh_dir}/
    chmod 644 ${ssh_dir}/authorized_keys

    echo $password | passwd --stdin $name
fi
