#!/usr/bin/env ruby

file_name = ARGV[0]
common_command   = ARGV[1]

p "open #{file_name}"
p "command is #{common_command}"
gem install mysql2 -- --with-mysql-config=/usr/local/bin/mysql_config

# open(file_name) do |f|
#   while line = f.gets
#     line.strip!
#     command = "gem install #{line}"
#     p command
#     system command
#   end
# end
#
