#
# This file is automatically generated on ReFe installation.
# You can override this value by setting REFE_DATA_DIR
# environment variable.
#
module ReFe
  REFE_DATA_DIR = '/Users/alpaca/.rbenv/versions/2.0.0-p247/share/refe'
end
