" controller
syn keyword rubyRailsMethod params request response session headers cookies flash
syn keyword rubyRailsRenderMethod render
syn keyword rubyRailsControllerMethod helper helper_method layout url_for serialize rescue_from
syn keyword rubyRailsRenderMethod head redirect_to render_to_string respond_with
syn keyword rubyRailsFilterMethod before_filter append_before_filter prepend_before_filter after_filter append_after_filter prepend_after_filter around_filter append_around_filter prepend_around_filter skip_before_filter skip_after_filter skip_filter
syn keyword rubyRailsactionMethod before_action append_before_action prepend_before_action after_action append_after_action prepend_after_action around_action append_around_action prepend_around_action skip_before_action skip_after_action skip_action
