[[plugins]]
repo = 'alpaca-tc/alpaca-switch-file.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'vim-scripts/repeat.vim'
on_map    = '<Plug>'

[[plugins]]
repo = 'vim-jp/vital.vim'
on_func = ['vital#of']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd    = ["QuickRun"]
on_map    = ["nxo", "<Plug>"]
on_source = ['vimproc']
depends   = ["vimproc"]
hook_source = '''
  let g:quickrun_config = {}
  let g:quickrun_no_default_key_mappings = 1

  let g:quickrun_config._ = {
        \ 'runner' : 'vimproc',
        \ }

  " let g:quickrun_config.javascript = {
  "       \ 'command': 'node'}

  let g:quickrun_config.java = {
        \   'exec': ['javac %o %s', '%c %s:t:r %a'],
        \   'hook/output_encode/encoding': '&termencoding',
        \   'hook/sweep/files': '%S:p:r.class',
        \ }

  let g:quickrun_config.lisp = {
        \ 'command': 'clisp' }

  let g:quickrun_config['coffee.compile'] = {
        \ 'command' : 'coffee',
        \ 'exec' : ['%c -cbp %s'] }

  let g:quickrun_config['coffee'] = { 'command' : 'coffee', }
  let g:quickrun_config['coffee.javascript'] = g:quickrun_config['coffee']

  let g:quickrun_config.markdown = {
        \ 'outputter': 'browser',
        \ 'cmdopt': '-s' }

  let g:quickrun_config['markdown.snowcrash'] = {
        \ 'command': 'snowcrash',
        \ 'cmdopt': '--format json'
        \ }

  let g:quickrun_config.applescript = {
        \ 'command' : 'osascript' , 'output' : '_'}

  let g:quickrun_config['racc.ruby'] = {
        \ 'command': 'racc',
        \ 'cmdopt' : '-o',
        \ 'args'   : 'main.rb',
        \ 'outputter': 'message',
        \ 'exec'   : '%c %o %a %s', }

  let g:quickrun_config['racc.run'] = {
        \ 'command': 'ruby',
        \ 'args'   : 'main.rb',
        \ 'exec'   : '%c %a src/', }

  let g:quickrun_config['ruby.rspec'] = {
        \ 'type' : 'ruby.rspec',
        \ 'command': 'rspec',
        \ 'exec': 'bundle exec %c %o %s', }

  let g:quickrun_config['racc.ruby'] = {}

  call quickrun#module#load('vimproc')

  augroup QuickRunAutoCmd
    autocmd!
    autocmd FileType quickrun call alpaca_window#set_smart_close()
  augroup END
'''


