kind=defined
names=new
visibility=public

--- new(addr, size = 0, free = nil)    -> DL::PtrData

アドレス addr を指すポインタに相当する PtrData オブジェクトを返します。

size を指定した場合、アドレス addr に確保されているメモリ領域のサイズは
size であるとします。
GC は free 関数を使用してメモリを解放します。

@param addr 生成する PtrData オブジェクトが指すアドレスを整数で指定します。

@param size 生成する PtrData オブジェクトが指すメモリ領域のサイズを整数で指定します。

@param free 生成する PtrData オブジェクトの free 関数を [[c:DL::Symbol]] で指定します。

